### ISSUE TITLE
image tracking status에 대한 이해 부족

### ISSUE THREAD

**Issue by hongsam14** [AR-Docent/AR_Docent#5]
tracking status는 3가지 상태가 존재한다.
<p style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 10px; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: Roboto, sans-serif; font-size: 14px;">There are three possible tracking states for<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-size: 12.600000381469727px; padding: 2px 4px; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; color: rgb(199, 37, 78); background-color: rgb(249, 242, 244); border-radius: 4px;">ARTrackedImages</code>:</p>

TrackingState | Description
-- | --
None | The image is not being tracked. Note that this may be the initial state when the image is first detected.
Limited | The image is being tracked, but not as well. The situations in which an image is considered Limited instead of Tracking depend on the underlying AR framework. Examples that may cause Limited tracking include: Obscuring the image so that it is not visible to the camera.The image is not tracked as a moving image. This can happen, for example, if the maxNumberOfMovingImages is exceeded.
Tracking | The underlying AR SDK reports that it is actively tracking the image.

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">There are three possible tracking states for ARTrackedImages:

TrackingState	Description
[None](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.TrackingState.html#UnityEngine_XR_ARSubsystems_TrackingState_None)	The image is not being tracked. Note that this may be the initial state when the image is first detected.
[Limited](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.TrackingState.html#UnityEngine_XR_ARSubsystems_TrackingState_Limited)	The image is being tracked, but not as well. The situations in which an image is considered Limited instead of Tracking depend on the underlying AR framework. Examples that may cause Limited tracking include:
Obscuring the image so that it is not visible to the camera.
The image is not tracked as a moving image. This can happen, for example, if the maxNumberOfMovingImages is exceeded.
[Tracking](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.1/api/UnityEngine.XR.ARSubsystems.TrackingState.html#UnityEngine_XR_ARSubsystems_TrackingState_Tracking)	The underlying AR SDK reports that it is actively tracking the image.

**Comment by hongsam14** [comment]
https://youtu.be/hz86QoxWBZ4

**Comment by jongfeel** [comment]
Limited는 미팅 때도 말씀드렸는데 성능상의 문제로 인해 카메라 상에서 tracking 하는데 큰 문제가 없어 보여도 일부러 limited로 제한 하는 경우도 있긴 합니다.

None 상태만 아니면 어쨌든 인식이 되고 tracking이 되는 상태라고 보면 됩니다.
